import { Repository, AuditResult, Preset } from '@/types';

export const MOCK_REPOS: Repository[] = [
  {
    id: '1',
    name: 'api-gateway',
    org: 'acmecorp',
    stack: 'Node.js',
    score: 92,
    isPrivate: true,
    updatedAt: '2h ago',
  },
  {
    id: '2',
    name: 'ml-pipeline',
    org: 'acmecorp',
    stack: 'Python',
    score: 61,
    isPrivate: false,
    updatedAt: '1d ago',
  },
  {
    id: '3',
    name: 'mobile-app',
    org: 'acmecorp',
    stack: 'React Native',
    score: 45,
    isPrivate: true,
    updatedAt: '3d ago',
  },
  {
    id: '4',
    name: 'data-service',
    org: 'acmecorp',
    stack: 'Go',
    score: 88,
    isPrivate: false,
    updatedAt: '5d ago',
  },
];

const PASSED_CHECKS = [
  { id: 'p1', title: 'License file present', description: 'Repository has a valid MIT license', severity: 'info' as const, fixable: false },
  { id: 'p2', title: 'README.md exists', description: 'Repository has a readme file', severity: 'info' as const, fixable: false },
  { id: 'p3', title: 'Gitignore configured', description: '.gitignore file is present and populated', severity: 'info' as const, fixable: false },
  { id: 'p4', title: 'Code of conduct', description: 'CODE_OF_CONDUCT.md is present', severity: 'info' as const, fixable: false },
  { id: 'p5', title: 'No sensitive data', description: 'No API keys or secrets detected in codebase', severity: 'info' as const, fixable: false },
  { id: 'p6', title: 'Dependency lock file', description: 'Lock file found (package-lock.json)', severity: 'info' as const, fixable: false },
  { id: 'p7', title: 'Semantic versioning', description: 'Package version follows semver format', severity: 'info' as const, fixable: false },
  { id: 'p8', title: 'Default branch named main', description: 'Using recommended branch name "main"', severity: 'info' as const, fixable: false },
  { id: 'p9', title: 'Repository description set', description: 'Repository has a description in GitHub', severity: 'info' as const, fixable: false },
  { id: 'p10', title: 'Topics/tags configured', description: 'Repository has relevant GitHub topics', severity: 'info' as const, fixable: false },
  { id: 'p11', title: 'No enormous files', description: 'No files larger than 50MB in history', severity: 'info' as const, fixable: false },
  { id: 'p12', title: 'Dependabot enabled', description: 'Automated dependency updates are configured', severity: 'info' as const, fixable: false },
  { id: 'p13', title: 'PR merge strategy set', description: 'Squash merge is the default strategy', severity: 'info' as const, fixable: false },
  { id: 'p14', title: 'Issue tracker enabled', description: 'GitHub Issues is turned on', severity: 'info' as const, fixable: false },
  { id: 'p15', title: 'Wiki disabled', description: 'Wiki is disabled (reducing noise)', severity: 'info' as const, fixable: false },
  { id: 'p16', title: 'Releases published', description: 'At least one GitHub Release exists', severity: 'info' as const, fixable: false },
  { id: 'p17', title: 'Auto-delete branches', description: 'Merged branches are auto-deleted', severity: 'info' as const, fixable: false },
  { id: 'p18', title: 'Commit signing', description: 'Recent commits are signed with GPG', severity: 'info' as const, fixable: false },
  { id: 'p19', title: 'Test coverage badge', description: 'Coverage badge present in README', severity: 'info' as const, fixable: false },
  { id: 'p20', title: 'Editor config present', description: '.editorconfig ensures consistent formatting', severity: 'info' as const, fixable: false },
  { id: 'p21', title: 'Linting configured', description: 'ESLint / Pylint config file found', severity: 'info' as const, fixable: false },
  { id: 'p22', title: 'Build status badge', description: 'CI status badge shown in README', severity: 'info' as const, fixable: false },
];

export const MOCK_AUDIT_RESULT: AuditResult = {
  repoId: '2',
  repoName: 'acmecorp/ml-pipeline',
  score: 74,
  totalChecks: 30,
  criticalIssues: [
    {
      id: 'c1',
      title: 'No branch protection on main',
      description: 'Allows direct pushes without review — anyone can overwrite history',
      severity: 'critical',
      fixable: true,
    },
    {
      id: 'c2',
      title: 'Missing CI/CD workflow',
      description: 'No automated testing pipeline found — bugs ship undetected',
      severity: 'critical',
      fixable: true,
    },
  ],
  warnings: [
    {
      id: 'w1',
      title: 'No SECURITY.md',
      description: 'Missing security disclosure policy for vulnerability reports',
      severity: 'warning',
      fixable: true,
    },
    {
      id: 'w2',
      title: 'README incomplete',
      description: 'No installation or usage section found in README',
      severity: 'warning',
      fixable: true,
    },
    {
      id: 'w3',
      title: 'No issue templates',
      description: 'Contributors have no structured guidance for bug reports',
      severity: 'warning',
      fixable: true,
    },
    {
      id: 'w4',
      title: 'No CONTRIBUTING.md',
      description: 'Missing contribution guidelines for new contributors',
      severity: 'warning',
      fixable: true,
    },
    {
      id: 'w5',
      title: 'Stale dependencies',
      description: '4 packages are more than 6 months behind latest version',
      severity: 'warning',
      fixable: false,
    },
    {
      id: 'w6',
      title: 'No PR template',
      description: 'Pull requests have no structured description template',
      severity: 'warning',
      fixable: true,
    },
  ],
  passed: PASSED_CHECKS,
};

export const MOCK_PRESETS: Preset[] = [
  {
    id: '1',
    name: 'Standard Node.js',
    appliedRepos: 8,
    lastModified: '1 week ago',
    settings: {
      requireBranchProtection: true,
      createCIDPipeline: true,
      addIssueTemplates: true,
      enforceCodeReview: true,
      addSecurityMD: false,
      addContributingMD: true,
      setUpEnvironments: false,
      stacks: ['Node.js'],
    },
  },
  {
    id: '2',
    name: 'Python Data Science',
    appliedRepos: 3,
    lastModified: '2 weeks ago',
    settings: {
      requireBranchProtection: true,
      createCIDPipeline: true,
      addIssueTemplates: false,
      enforceCodeReview: true,
      addSecurityMD: false,
      addContributingMD: true,
      setUpEnvironments: true,
      stacks: ['Python'],
    },
  },
  {
    id: '3',
    name: 'Enterprise Compliance',
    appliedRepos: 1,
    lastModified: '3 days ago',
    settings: {
      requireBranchProtection: true,
      createCIDPipeline: true,
      addIssueTemplates: true,
      enforceCodeReview: true,
      addSecurityMD: true,
      addContributingMD: true,
      setUpEnvironments: true,
      stacks: ['Node.js', 'Python', 'Go', 'Java'],
    },
  },
];

export const MOCK_AUDIT_BY_REPO: Record<string, AuditResult> = {
  '1': {
    repoId: '1',
    repoName: 'acmecorp/api-gateway',
    score: 92,
    totalChecks: 30,
    criticalIssues: [],
    warnings: [
      { id: 'w1', title: 'No SECURITY.md', description: 'Missing security disclosure policy', severity: 'warning', fixable: true },
      { id: 'w2', title: 'Stale dependencies', description: '2 packages are behind latest version', severity: 'warning', fixable: false },
    ],
    passed: PASSED_CHECKS,
  },
  '2': MOCK_AUDIT_RESULT,
  '3': {
    repoId: '3',
    repoName: 'acmecorp/mobile-app',
    score: 45,
    totalChecks: 30,
    criticalIssues: [
      { id: 'c1', title: 'No branch protection on main', description: 'Allows direct pushes without review', severity: 'critical', fixable: true },
      { id: 'c2', title: 'Missing CI/CD workflow', description: 'No automated testing pipeline found', severity: 'critical', fixable: true },
      { id: 'c3', title: 'No tests detected', description: 'No test files found in the repository', severity: 'critical', fixable: false },
    ],
    warnings: [
      { id: 'w1', title: 'No SECURITY.md', description: 'Missing security disclosure policy', severity: 'warning', fixable: true },
      { id: 'w2', title: 'README incomplete', description: 'No installation or usage section found', severity: 'warning', fixable: true },
      { id: 'w3', title: 'No issue templates', description: 'Contributors have no guidance for bug reports', severity: 'warning', fixable: true },
      { id: 'w4', title: 'No CONTRIBUTING.md', description: 'Missing contribution guidelines', severity: 'warning', fixable: true },
    ],
    passed: PASSED_CHECKS.slice(0, 10),
  },
  '4': {
    repoId: '4',
    repoName: 'acmecorp/data-service',
    score: 88,
    totalChecks: 30,
    criticalIssues: [],
    warnings: [
      { id: 'w1', title: 'No SECURITY.md', description: 'Missing security disclosure policy', severity: 'warning', fixable: true },
      { id: 'w2', title: 'No issue templates', description: 'Contributors have no guidance for bug reports', severity: 'warning', fixable: true },
      { id: 'w3', title: 'README incomplete', description: 'No usage examples in README', severity: 'warning', fixable: true },
    ],
    passed: PASSED_CHECKS,
  },
};
